Add missing target for H7 (HCD)
ObKo/stm32-cmake pull request #255
Opened 2021-08-02 10:21 UTC by zisi

When in H7 want to use HCD `HAL::STM32::H7::M7::HCD`, it returns error

```
CMake Error at test/CMakeLists.txt:1 (add_executable):
  Target "test" links to target "HAL::STM32::H7::M7::HCD" but the target was                                                                                                                   
  not found.  Perhaps a find_package() call is missing for an IMPORTED                                                                                                                         
  target, or an ALIAS target is missing? 
```

Signed-off-by: Agis Zisimatos <agzisim@gmail.com>

2021-08-02 15:06 UTC, atsju requested changes
Thank you for this pull request. I think you spotted an evolution of the HAL.
could you please have a look at whole [HAL](https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Drivers/STM32H7xx_HAL_Driver/Src) and add all missing modules (cordic, fmac, ...)

2021-08-03 11:18 UTC, zisi commented
I think, i have added all missing modules.

2021-08-03 11:36 UTC, atsju requested changes

2021-08-03 11:36 UTC, atsju commented on cmake/FindHAL.cmake
>      lpuart mdma opamp pwr rcc rng rtc sdmmc spi swpmi tim usart usb utils
```suggestion
    adc bdma comp cordic crc crs dac delayblock dma dma2d exti fmac fmc gpio hrtim i2c lptim
    lpuart mdma opamp pwr rcc rng rtc sdmmc spi swpmi tim usart usb utils
```

2021-08-03 11:37 UTC, atsju approved these changes
You missed one. I have added it. 
Thank you.

2021-08-03 11:43 UTC, atsju approved these changes

2021-08-03 11:43 UTC, atsju commented on cmake/FindHAL.cmake
> +    adc cec comp cordix cortex crc cryp dac dcmi dfsdm dma dma2d dsi dts eth exti fdcan
```suggestion
    adc cec comp cordic cortex crc cryp dac dcmi dfsdm dma dma2d dsi dts eth exti fdcan
```

2021-08-03 15:02 UTC, Hish15 approved these changes

2021-08-03 15:02 UTC, merged