Added stm32_generate_srec_file to generate Motorola S-record files
ObKo/stm32-cmake pull request #271
Opened 2021-08-19 10:12 UTC by smokeythebandit

2021-08-19 17:26 UTC, Hish15 approved these changes

2021-08-23 06:14 UTC, atsju requested changes

2021-08-23 06:14 UTC, atsju commented on cmake/stm32/common.cmake
> +        BYPRODUCTS ${TARGET}.hex
```suggestion
        BYPRODUCTS ${TARGET}.srec

```

2021-08-23 06:15 UTC, atsju approved these changes

2021-08-23 06:26 UTC, Hish15 approved these changes

2021-08-23 06:26 UTC, merged