Split devices in family files
ObKo/stm32-cmake pull request #341
Opened 2024-05-12 13:01 UTC by xanthio

Contribution aiming to ease project maintenance:

1. We want to get rid off the large cube/cmsis/hal lists because:
    - they become larger when ST releases new families
    - concurrent  PR for updates create conflicts are they touch the same lines
2. I think minimizing the amount of file edited to introduction new family would encourage contributions

This major change was the opportunity to use the latest version of each ST repo.
But this needs 2 changes:

1. Better definition of shared memory block MB2 in generated `linker script` because WB startup initializes this memory area
2. Add a definition for MP1 family because clocks default values are set in HAL and CMSIS `system_<device>.c` doesn't include it if `USE_HAL_DRIVER` is not defined

2024-05-12 13:02 UTC, xanthio commented
@Hish15: Here is the first maintenance PR

2024-05-20 12:17 UTC, Hish15 requested changes
WIP : I checked that all devices are properly moved 👍🏿 
The CUBE/CMSIS/HAL must not be changed in this PR

2024-05-20 12:17 UTC, Hish15 commented on cmake/stm32/f0.cmake
> +set(HAL_F0_VERSION   v1.7.8)
Don't change anything on PR that moves so many things around
```suggestion
set(CUBE_F0_VERSION  v1.11.2)
set(CMSIS_F0_VERSION v2.3.5)
set(HAL_F0_VERSION   v1.7.5)

```

2024-05-20 12:17 UTC, Hish15 commented on cmake/stm32/f1.cmake
> +set(HAL_F1_VERSION   v1.1.9)
```suggestion
set(CUBE_F1_VERSION  v1.8.4)
set(CMSIS_F1_VERSION v4.3.3)
set(HAL_F1_VERSION   v1.1.8)

```

2024-05-20 12:17 UTC, Hish15 commented on cmake/stm32/f2.cmake
> +set(HAL_F2_VERSION   v1.2.8)
```suggestion
set(CUBE_F2_VERSION  v1.9.3)
set(CMSIS_F2_VERSION v2.2.5)
set(HAL_F2_VERSION   v1.2.7)
```

2024-05-20 12:17 UTC, Hish15 commented on cmake/stm32/f3.cmake
> +set(HAL_F3_VERSION   v1.5.8)
```suggestion
set(CUBE_F3_VERSION  v1.11.2)
set(CMSIS_F3_VERSION v2.3.5)
set(HAL_F3_VERSION   v1.5.5)
```

2024-05-20 12:17 UTC, Hish15 commented on cmake/stm32/g4.cmake
> +set(HAL_G4_VERSION   v1.2.3)
```suggestion
set(CUBE_G4_VERSION  v1.4.0)
set(CMSIS_G4_VERSION v1.2.1)
set(HAL_G4_VERSION   v1.2.1)
```

2024-05-21 21:22 UTC, Hish15 approved these changes
@atsju please have a look and merge this, for me it's good to go.

2024-05-24 19:10 UTC, merged